### ISSUE TITLE
Documentation: crates.io Documentation link is broken

### ISSUE THREAD

**Issue by ncoish** [alexcrichton/bufstream#10]
The crates.io page for [bufstream](https://crates.io/crates/bufstream) currently has a broken documentation link that tries to bring you to [http://alexcrichton.com/bufstream](http://alexcrichton.com/bufstream). 

As I'm sure you know, the docs are now hosted at [doc.rs](https://docs.rs/bufstream/0.1.3/bufstream/) 😄

**Comment by alexcrichton** [comment]
Oops, thanks for the heads up!
